/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as CuentaRouteImport } from './routes/cuenta'
import { Route as BienvenidaRouteImport } from './routes/bienvenida'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AliasRouteImport } from './routes/$alias'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PEmpresaLocalIndexRouteImport } from './routes/p.$empresa.$local.index'
import { Route as PEmpresaLocalCarritoRouteImport } from './routes/p.$empresa.$local.carrito'
import { Route as TEmpresaLocalTotemIndexRouteImport } from './routes/t.$empresa.$local.$totem.index'
import { Route as TEmpresaLocalTotemCombosRouteImport } from './routes/t.$empresa.$local.$totem.combos'
import { Route as TEmpresaLocalTotemCheckoutRouteImport } from './routes/t.$empresa.$local.$totem.checkout'
import { Route as TEmpresaLocalTotemCategoriasRouteImport } from './routes/t.$empresa.$local.$totem.categorias'
import { Route as TEmpresaLocalTotemCarritoRouteImport } from './routes/t.$empresa.$local.$totem.carrito'
import { Route as PEmpresaLocalPedidoTokenRouteImport } from './routes/p.$empresa.$local.pedido.$token'
import { Route as TEmpresaLocalTotemPagarOrderIdRouteImport } from './routes/t.$empresa.$local.$totem.pagar.$orderId'
import { Route as TEmpresaLocalTotemMenuCategoryRouteImport } from './routes/t.$empresa.$local.$totem.menu.$category'
import { Route as TEmpresaLocalTotemListoOrderIdRouteImport } from './routes/t.$empresa.$local.$totem.listo.$orderId'

const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentaRoute = CuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const BienvenidaRoute = BienvenidaRouteImport.update({
  id: '/bienvenida',
  path: '/bienvenida',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AliasRoute = AliasRouteImport.update({
  id: '/$alias',
  path: '/$alias',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PEmpresaLocalIndexRoute = PEmpresaLocalIndexRouteImport.update({
  id: '/p/$empresa/$local/',
  path: '/p/$empresa/$local/',
  getParentRoute: () => rootRouteImport,
} as any)
const PEmpresaLocalCarritoRoute = PEmpresaLocalCarritoRouteImport.update({
  id: '/p/$empresa/$local/carrito',
  path: '/p/$empresa/$local/carrito',
  getParentRoute: () => rootRouteImport,
} as any)
const TEmpresaLocalTotemIndexRoute = TEmpresaLocalTotemIndexRouteImport.update({
  id: '/t/$empresa/$local/$totem/',
  path: '/t/$empresa/$local/$totem/',
  getParentRoute: () => rootRouteImport,
} as any)
const TEmpresaLocalTotemCombosRoute =
  TEmpresaLocalTotemCombosRouteImport.update({
    id: '/t/$empresa/$local/$totem/combos',
    path: '/t/$empresa/$local/$totem/combos',
    getParentRoute: () => rootRouteImport,
  } as any)
const TEmpresaLocalTotemCheckoutRoute =
  TEmpresaLocalTotemCheckoutRouteImport.update({
    id: '/t/$empresa/$local/$totem/checkout',
    path: '/t/$empresa/$local/$totem/checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const TEmpresaLocalTotemCategoriasRoute =
  TEmpresaLocalTotemCategoriasRouteImport.update({
    id: '/t/$empresa/$local/$totem/categorias',
    path: '/t/$empresa/$local/$totem/categorias',
    getParentRoute: () => rootRouteImport,
  } as any)
const TEmpresaLocalTotemCarritoRoute =
  TEmpresaLocalTotemCarritoRouteImport.update({
    id: '/t/$empresa/$local/$totem/carrito',
    path: '/t/$empresa/$local/$totem/carrito',
    getParentRoute: () => rootRouteImport,
  } as any)
const PEmpresaLocalPedidoTokenRoute =
  PEmpresaLocalPedidoTokenRouteImport.update({
    id: '/p/$empresa/$local/pedido/$token',
    path: '/p/$empresa/$local/pedido/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const TEmpresaLocalTotemPagarOrderIdRoute =
  TEmpresaLocalTotemPagarOrderIdRouteImport.update({
    id: '/t/$empresa/$local/$totem/pagar/$orderId',
    path: '/t/$empresa/$local/$totem/pagar/$orderId',
    getParentRoute: () => rootRouteImport,
  } as any)
const TEmpresaLocalTotemMenuCategoryRoute =
  TEmpresaLocalTotemMenuCategoryRouteImport.update({
    id: '/t/$empresa/$local/$totem/menu/$category',
    path: '/t/$empresa/$local/$totem/menu/$category',
    getParentRoute: () => rootRouteImport,
  } as any)
const TEmpresaLocalTotemListoOrderIdRoute =
  TEmpresaLocalTotemListoOrderIdRouteImport.update({
    id: '/t/$empresa/$local/$totem/listo/$orderId',
    path: '/t/$empresa/$local/$totem/listo/$orderId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$alias': typeof AliasRoute
  '/admin': typeof AdminRoute
  '/bienvenida': typeof BienvenidaRoute
  '/cuenta': typeof CuentaRoute
  '/kitchen': typeof KitchenRoute
  '/login': typeof LoginRoute
  '/superadmin': typeof SuperadminRoute
  '/p/$empresa/$local/carrito': typeof PEmpresaLocalCarritoRoute
  '/p/$empresa/$local/': typeof PEmpresaLocalIndexRoute
  '/p/$empresa/$local/pedido/$token': typeof PEmpresaLocalPedidoTokenRoute
  '/t/$empresa/$local/$totem/carrito': typeof TEmpresaLocalTotemCarritoRoute
  '/t/$empresa/$local/$totem/categorias': typeof TEmpresaLocalTotemCategoriasRoute
  '/t/$empresa/$local/$totem/checkout': typeof TEmpresaLocalTotemCheckoutRoute
  '/t/$empresa/$local/$totem/combos': typeof TEmpresaLocalTotemCombosRoute
  '/t/$empresa/$local/$totem/': typeof TEmpresaLocalTotemIndexRoute
  '/t/$empresa/$local/$totem/listo/$orderId': typeof TEmpresaLocalTotemListoOrderIdRoute
  '/t/$empresa/$local/$totem/menu/$category': typeof TEmpresaLocalTotemMenuCategoryRoute
  '/t/$empresa/$local/$totem/pagar/$orderId': typeof TEmpresaLocalTotemPagarOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$alias': typeof AliasRoute
  '/admin': typeof AdminRoute
  '/bienvenida': typeof BienvenidaRoute
  '/cuenta': typeof CuentaRoute
  '/kitchen': typeof KitchenRoute
  '/login': typeof LoginRoute
  '/superadmin': typeof SuperadminRoute
  '/p/$empresa/$local/carrito': typeof PEmpresaLocalCarritoRoute
  '/p/$empresa/$local': typeof PEmpresaLocalIndexRoute
  '/p/$empresa/$local/pedido/$token': typeof PEmpresaLocalPedidoTokenRoute
  '/t/$empresa/$local/$totem/carrito': typeof TEmpresaLocalTotemCarritoRoute
  '/t/$empresa/$local/$totem/categorias': typeof TEmpresaLocalTotemCategoriasRoute
  '/t/$empresa/$local/$totem/checkout': typeof TEmpresaLocalTotemCheckoutRoute
  '/t/$empresa/$local/$totem/combos': typeof TEmpresaLocalTotemCombosRoute
  '/t/$empresa/$local/$totem': typeof TEmpresaLocalTotemIndexRoute
  '/t/$empresa/$local/$totem/listo/$orderId': typeof TEmpresaLocalTotemListoOrderIdRoute
  '/t/$empresa/$local/$totem/menu/$category': typeof TEmpresaLocalTotemMenuCategoryRoute
  '/t/$empresa/$local/$totem/pagar/$orderId': typeof TEmpresaLocalTotemPagarOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$alias': typeof AliasRoute
  '/admin': typeof AdminRoute
  '/bienvenida': typeof BienvenidaRoute
  '/cuenta': typeof CuentaRoute
  '/kitchen': typeof KitchenRoute
  '/login': typeof LoginRoute
  '/superadmin': typeof SuperadminRoute
  '/p/$empresa/$local/carrito': typeof PEmpresaLocalCarritoRoute
  '/p/$empresa/$local/': typeof PEmpresaLocalIndexRoute
  '/p/$empresa/$local/pedido/$token': typeof PEmpresaLocalPedidoTokenRoute
  '/t/$empresa/$local/$totem/carrito': typeof TEmpresaLocalTotemCarritoRoute
  '/t/$empresa/$local/$totem/categorias': typeof TEmpresaLocalTotemCategoriasRoute
  '/t/$empresa/$local/$totem/checkout': typeof TEmpresaLocalTotemCheckoutRoute
  '/t/$empresa/$local/$totem/combos': typeof TEmpresaLocalTotemCombosRoute
  '/t/$empresa/$local/$totem/': typeof TEmpresaLocalTotemIndexRoute
  '/t/$empresa/$local/$totem/listo/$orderId': typeof TEmpresaLocalTotemListoOrderIdRoute
  '/t/$empresa/$local/$totem/menu/$category': typeof TEmpresaLocalTotemMenuCategoryRoute
  '/t/$empresa/$local/$totem/pagar/$orderId': typeof TEmpresaLocalTotemPagarOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$alias'
    | '/admin'
    | '/bienvenida'
    | '/cuenta'
    | '/kitchen'
    | '/login'
    | '/superadmin'
    | '/p/$empresa/$local/carrito'
    | '/p/$empresa/$local/'
    | '/p/$empresa/$local/pedido/$token'
    | '/t/$empresa/$local/$totem/carrito'
    | '/t/$empresa/$local/$totem/categorias'
    | '/t/$empresa/$local/$totem/checkout'
    | '/t/$empresa/$local/$totem/combos'
    | '/t/$empresa/$local/$totem/'
    | '/t/$empresa/$local/$totem/listo/$orderId'
    | '/t/$empresa/$local/$totem/menu/$category'
    | '/t/$empresa/$local/$totem/pagar/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$alias'
    | '/admin'
    | '/bienvenida'
    | '/cuenta'
    | '/kitchen'
    | '/login'
    | '/superadmin'
    | '/p/$empresa/$local/carrito'
    | '/p/$empresa/$local'
    | '/p/$empresa/$local/pedido/$token'
    | '/t/$empresa/$local/$totem/carrito'
    | '/t/$empresa/$local/$totem/categorias'
    | '/t/$empresa/$local/$totem/checkout'
    | '/t/$empresa/$local/$totem/combos'
    | '/t/$empresa/$local/$totem'
    | '/t/$empresa/$local/$totem/listo/$orderId'
    | '/t/$empresa/$local/$totem/menu/$category'
    | '/t/$empresa/$local/$totem/pagar/$orderId'
  id:
    | '__root__'
    | '/'
    | '/$alias'
    | '/admin'
    | '/bienvenida'
    | '/cuenta'
    | '/kitchen'
    | '/login'
    | '/superadmin'
    | '/p/$empresa/$local/carrito'
    | '/p/$empresa/$local/'
    | '/p/$empresa/$local/pedido/$token'
    | '/t/$empresa/$local/$totem/carrito'
    | '/t/$empresa/$local/$totem/categorias'
    | '/t/$empresa/$local/$totem/checkout'
    | '/t/$empresa/$local/$totem/combos'
    | '/t/$empresa/$local/$totem/'
    | '/t/$empresa/$local/$totem/listo/$orderId'
    | '/t/$empresa/$local/$totem/menu/$category'
    | '/t/$empresa/$local/$totem/pagar/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AliasRoute: typeof AliasRoute
  AdminRoute: typeof AdminRoute
  BienvenidaRoute: typeof BienvenidaRoute
  CuentaRoute: typeof CuentaRoute
  KitchenRoute: typeof KitchenRoute
  LoginRoute: typeof LoginRoute
  SuperadminRoute: typeof SuperadminRoute
  PEmpresaLocalCarritoRoute: typeof PEmpresaLocalCarritoRoute
  PEmpresaLocalIndexRoute: typeof PEmpresaLocalIndexRoute
  PEmpresaLocalPedidoTokenRoute: typeof PEmpresaLocalPedidoTokenRoute
  TEmpresaLocalTotemCarritoRoute: typeof TEmpresaLocalTotemCarritoRoute
  TEmpresaLocalTotemCategoriasRoute: typeof TEmpresaLocalTotemCategoriasRoute
  TEmpresaLocalTotemCheckoutRoute: typeof TEmpresaLocalTotemCheckoutRoute
  TEmpresaLocalTotemCombosRoute: typeof TEmpresaLocalTotemCombosRoute
  TEmpresaLocalTotemIndexRoute: typeof TEmpresaLocalTotemIndexRoute
  TEmpresaLocalTotemListoOrderIdRoute: typeof TEmpresaLocalTotemListoOrderIdRoute
  TEmpresaLocalTotemMenuCategoryRoute: typeof TEmpresaLocalTotemMenuCategoryRoute
  TEmpresaLocalTotemPagarOrderIdRoute: typeof TEmpresaLocalTotemPagarOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuenta': {
      id: '/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof CuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bienvenida': {
      id: '/bienvenida'
      path: '/bienvenida'
      fullPath: '/bienvenida'
      preLoaderRoute: typeof BienvenidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$alias': {
      id: '/$alias'
      path: '/$alias'
      fullPath: '/$alias'
      preLoaderRoute: typeof AliasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$empresa/$local/': {
      id: '/p/$empresa/$local/'
      path: '/p/$empresa/$local'
      fullPath: '/p/$empresa/$local/'
      preLoaderRoute: typeof PEmpresaLocalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$empresa/$local/carrito': {
      id: '/p/$empresa/$local/carrito'
      path: '/p/$empresa/$local/carrito'
      fullPath: '/p/$empresa/$local/carrito'
      preLoaderRoute: typeof PEmpresaLocalCarritoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$empresa/$local/$totem/': {
      id: '/t/$empresa/$local/$totem/'
      path: '/t/$empresa/$local/$totem'
      fullPath: '/t/$empresa/$local/$totem/'
      preLoaderRoute: typeof TEmpresaLocalTotemIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$empresa/$local/$totem/combos': {
      id: '/t/$empresa/$local/$totem/combos'
      path: '/t/$empresa/$local/$totem/combos'
      fullPath: '/t/$empresa/$local/$totem/combos'
      preLoaderRoute: typeof TEmpresaLocalTotemCombosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$empresa/$local/$totem/checkout': {
      id: '/t/$empresa/$local/$totem/checkout'
      path: '/t/$empresa/$local/$totem/checkout'
      fullPath: '/t/$empresa/$local/$totem/checkout'
      preLoaderRoute: typeof TEmpresaLocalTotemCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$empresa/$local/$totem/categorias': {
      id: '/t/$empresa/$local/$totem/categorias'
      path: '/t/$empresa/$local/$totem/categorias'
      fullPath: '/t/$empresa/$local/$totem/categorias'
      preLoaderRoute: typeof TEmpresaLocalTotemCategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$empresa/$local/$totem/carrito': {
      id: '/t/$empresa/$local/$totem/carrito'
      path: '/t/$empresa/$local/$totem/carrito'
      fullPath: '/t/$empresa/$local/$totem/carrito'
      preLoaderRoute: typeof TEmpresaLocalTotemCarritoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$empresa/$local/pedido/$token': {
      id: '/p/$empresa/$local/pedido/$token'
      path: '/p/$empresa/$local/pedido/$token'
      fullPath: '/p/$empresa/$local/pedido/$token'
      preLoaderRoute: typeof PEmpresaLocalPedidoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$empresa/$local/$totem/pagar/$orderId': {
      id: '/t/$empresa/$local/$totem/pagar/$orderId'
      path: '/t/$empresa/$local/$totem/pagar/$orderId'
      fullPath: '/t/$empresa/$local/$totem/pagar/$orderId'
      preLoaderRoute: typeof TEmpresaLocalTotemPagarOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$empresa/$local/$totem/menu/$category': {
      id: '/t/$empresa/$local/$totem/menu/$category'
      path: '/t/$empresa/$local/$totem/menu/$category'
      fullPath: '/t/$empresa/$local/$totem/menu/$category'
      preLoaderRoute: typeof TEmpresaLocalTotemMenuCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$empresa/$local/$totem/listo/$orderId': {
      id: '/t/$empresa/$local/$totem/listo/$orderId'
      path: '/t/$empresa/$local/$totem/listo/$orderId'
      fullPath: '/t/$empresa/$local/$totem/listo/$orderId'
      preLoaderRoute: typeof TEmpresaLocalTotemListoOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AliasRoute: AliasRoute,
  AdminRoute: AdminRoute,
  BienvenidaRoute: BienvenidaRoute,
  CuentaRoute: CuentaRoute,
  KitchenRoute: KitchenRoute,
  LoginRoute: LoginRoute,
  SuperadminRoute: SuperadminRoute,
  PEmpresaLocalCarritoRoute: PEmpresaLocalCarritoRoute,
  PEmpresaLocalIndexRoute: PEmpresaLocalIndexRoute,
  PEmpresaLocalPedidoTokenRoute: PEmpresaLocalPedidoTokenRoute,
  TEmpresaLocalTotemCarritoRoute: TEmpresaLocalTotemCarritoRoute,
  TEmpresaLocalTotemCategoriasRoute: TEmpresaLocalTotemCategoriasRoute,
  TEmpresaLocalTotemCheckoutRoute: TEmpresaLocalTotemCheckoutRoute,
  TEmpresaLocalTotemCombosRoute: TEmpresaLocalTotemCombosRoute,
  TEmpresaLocalTotemIndexRoute: TEmpresaLocalTotemIndexRoute,
  TEmpresaLocalTotemListoOrderIdRoute: TEmpresaLocalTotemListoOrderIdRoute,
  TEmpresaLocalTotemMenuCategoryRoute: TEmpresaLocalTotemMenuCategoryRoute,
  TEmpresaLocalTotemPagarOrderIdRoute: TEmpresaLocalTotemPagarOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
