/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TSlugIndexRouteImport } from './routes/t.$slug.index'
import { Route as TSlugCombosRouteImport } from './routes/t.$slug.combos'
import { Route as TSlugCheckoutRouteImport } from './routes/t.$slug.checkout'
import { Route as TSlugCategoriasRouteImport } from './routes/t.$slug.categorias'
import { Route as TSlugCarritoRouteImport } from './routes/t.$slug.carrito'
import { Route as TSlugMenuCategoryRouteImport } from './routes/t.$slug.menu.$category'
import { Route as TSlugListoOrderIdRouteImport } from './routes/t.$slug.listo.$orderId'

const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugIndexRoute = TSlugIndexRouteImport.update({
  id: '/t/$slug/',
  path: '/t/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugCombosRoute = TSlugCombosRouteImport.update({
  id: '/t/$slug/combos',
  path: '/t/$slug/combos',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugCheckoutRoute = TSlugCheckoutRouteImport.update({
  id: '/t/$slug/checkout',
  path: '/t/$slug/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugCategoriasRoute = TSlugCategoriasRouteImport.update({
  id: '/t/$slug/categorias',
  path: '/t/$slug/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugCarritoRoute = TSlugCarritoRouteImport.update({
  id: '/t/$slug/carrito',
  path: '/t/$slug/carrito',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugMenuCategoryRoute = TSlugMenuCategoryRouteImport.update({
  id: '/t/$slug/menu/$category',
  path: '/t/$slug/menu/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugListoOrderIdRoute = TSlugListoOrderIdRouteImport.update({
  id: '/t/$slug/listo/$orderId',
  path: '/t/$slug/listo/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/kitchen': typeof KitchenRoute
  '/login': typeof LoginRoute
  '/superadmin': typeof SuperadminRoute
  '/t/$slug/carrito': typeof TSlugCarritoRoute
  '/t/$slug/categorias': typeof TSlugCategoriasRoute
  '/t/$slug/checkout': typeof TSlugCheckoutRoute
  '/t/$slug/combos': typeof TSlugCombosRoute
  '/t/$slug/': typeof TSlugIndexRoute
  '/t/$slug/listo/$orderId': typeof TSlugListoOrderIdRoute
  '/t/$slug/menu/$category': typeof TSlugMenuCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/kitchen': typeof KitchenRoute
  '/login': typeof LoginRoute
  '/superadmin': typeof SuperadminRoute
  '/t/$slug/carrito': typeof TSlugCarritoRoute
  '/t/$slug/categorias': typeof TSlugCategoriasRoute
  '/t/$slug/checkout': typeof TSlugCheckoutRoute
  '/t/$slug/combos': typeof TSlugCombosRoute
  '/t/$slug': typeof TSlugIndexRoute
  '/t/$slug/listo/$orderId': typeof TSlugListoOrderIdRoute
  '/t/$slug/menu/$category': typeof TSlugMenuCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/kitchen': typeof KitchenRoute
  '/login': typeof LoginRoute
  '/superadmin': typeof SuperadminRoute
  '/t/$slug/carrito': typeof TSlugCarritoRoute
  '/t/$slug/categorias': typeof TSlugCategoriasRoute
  '/t/$slug/checkout': typeof TSlugCheckoutRoute
  '/t/$slug/combos': typeof TSlugCombosRoute
  '/t/$slug/': typeof TSlugIndexRoute
  '/t/$slug/listo/$orderId': typeof TSlugListoOrderIdRoute
  '/t/$slug/menu/$category': typeof TSlugMenuCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/kitchen'
    | '/login'
    | '/superadmin'
    | '/t/$slug/carrito'
    | '/t/$slug/categorias'
    | '/t/$slug/checkout'
    | '/t/$slug/combos'
    | '/t/$slug/'
    | '/t/$slug/listo/$orderId'
    | '/t/$slug/menu/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/kitchen'
    | '/login'
    | '/superadmin'
    | '/t/$slug/carrito'
    | '/t/$slug/categorias'
    | '/t/$slug/checkout'
    | '/t/$slug/combos'
    | '/t/$slug'
    | '/t/$slug/listo/$orderId'
    | '/t/$slug/menu/$category'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/kitchen'
    | '/login'
    | '/superadmin'
    | '/t/$slug/carrito'
    | '/t/$slug/categorias'
    | '/t/$slug/checkout'
    | '/t/$slug/combos'
    | '/t/$slug/'
    | '/t/$slug/listo/$orderId'
    | '/t/$slug/menu/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  KitchenRoute: typeof KitchenRoute
  LoginRoute: typeof LoginRoute
  SuperadminRoute: typeof SuperadminRoute
  TSlugCarritoRoute: typeof TSlugCarritoRoute
  TSlugCategoriasRoute: typeof TSlugCategoriasRoute
  TSlugCheckoutRoute: typeof TSlugCheckoutRoute
  TSlugCombosRoute: typeof TSlugCombosRoute
  TSlugIndexRoute: typeof TSlugIndexRoute
  TSlugListoOrderIdRoute: typeof TSlugListoOrderIdRoute
  TSlugMenuCategoryRoute: typeof TSlugMenuCategoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug/': {
      id: '/t/$slug/'
      path: '/t/$slug'
      fullPath: '/t/$slug/'
      preLoaderRoute: typeof TSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug/combos': {
      id: '/t/$slug/combos'
      path: '/t/$slug/combos'
      fullPath: '/t/$slug/combos'
      preLoaderRoute: typeof TSlugCombosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug/checkout': {
      id: '/t/$slug/checkout'
      path: '/t/$slug/checkout'
      fullPath: '/t/$slug/checkout'
      preLoaderRoute: typeof TSlugCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug/categorias': {
      id: '/t/$slug/categorias'
      path: '/t/$slug/categorias'
      fullPath: '/t/$slug/categorias'
      preLoaderRoute: typeof TSlugCategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug/carrito': {
      id: '/t/$slug/carrito'
      path: '/t/$slug/carrito'
      fullPath: '/t/$slug/carrito'
      preLoaderRoute: typeof TSlugCarritoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug/menu/$category': {
      id: '/t/$slug/menu/$category'
      path: '/t/$slug/menu/$category'
      fullPath: '/t/$slug/menu/$category'
      preLoaderRoute: typeof TSlugMenuCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug/listo/$orderId': {
      id: '/t/$slug/listo/$orderId'
      path: '/t/$slug/listo/$orderId'
      fullPath: '/t/$slug/listo/$orderId'
      preLoaderRoute: typeof TSlugListoOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  KitchenRoute: KitchenRoute,
  LoginRoute: LoginRoute,
  SuperadminRoute: SuperadminRoute,
  TSlugCarritoRoute: TSlugCarritoRoute,
  TSlugCategoriasRoute: TSlugCategoriasRoute,
  TSlugCheckoutRoute: TSlugCheckoutRoute,
  TSlugCombosRoute: TSlugCombosRoute,
  TSlugIndexRoute: TSlugIndexRoute,
  TSlugListoOrderIdRoute: TSlugListoOrderIdRoute,
  TSlugMenuCategoryRoute: TSlugMenuCategoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
